### ISSUE TITLE
Chapter 7 - Python Code error

### ISSUE THREAD

**Issue by jeetdholakia** [OpenCVBlueprints/OpenCVBlueprints#21]
Hi,

I'm running the python code given in chapter 7 after importing the video and gyroscope files on a mac. The application crashes in the meshwarp function with the following stack trace.
  
```
Traceback (most recent call last):
  File "/Users/jeetdholakia/PycharmProjects/HyperlapseTest/stable.py", line 601, in <module>
    stabilize_video(mp4path, csvpath)
  File "/Users/jeetdholakia/PycharmProjects/HyperlapseTest/stable.py", line 577, in stabilize_video
    prev, focal_length, gyro_delay, gyro_drift);
  File "/Users/jeetdholakia/PycharmProjects/HyperlapseTest/stable.py", line 265, in accumulateRotation
    o = utilities.meshwarp(src, pts_transformed)
  File "/Users/jeetdholakia/PycharmProjects/HyperlapseTest/utilities.py", line 120, in meshwarp
    mapx = np.append([], [ar[:,0] for ar in g_out]).reshape(mapsize).astype('float32')
ValueError: cannot reshape array of size 2332800 into shape (1080,1080,1)

```

The line which produces the error is:
```
utilities.py -> def meshwarp(src, distorted_grid)
mapx = np.append([], [ar[:,0] for ar in g_out]).reshape(mapsize).astype('float32')
```

P.S. - There are small errors in other classes as well, which required minor changes in code to get it up and running, they include :

1. Removing calibration_worker import (module not found error!) and importing `from calibration import GyroscopeDataFile` to make the gyroscope data work.
2. The gyroscope file generated does not have the extension .gyro.csv, its just XYZgyro.csv, where as python code looks for the aforementioned extension. 
3. `pts_transformed` variable in `def accumulateRotation`, is not initialized anywhere, hence i initialized it as an empty array `pts_transformed = []` in the beginning of that function.
4. In the same function, the supplied code `output = cv2.perspectiveTransform(np.array([[pixel_x, pixel_y]], transform) ` throws up numpy error `data type could not be understood`. Hence, I changed it to` output = cv2.perspectiveTransform(np.array([[pixel_x, pixel_y]], dtype="float32"),transform)`, and the code worked. 

Please let me know how to fix the aforementioned issue, and if I have made any mistakes while correcting the code which threw some compile time and run time errors. 

Thanks, 
Jeet

**Comment by StevenPuttemans** [comment]
@liquidmetal Utkarsh, found the issue? Will you follow up on this or you want one of us to take a look at this?

**Comment by liquidmetal** [comment]
@jeetdholakia Thanks so much for fixing all the other errors! I've incorporated your changes in the repo here. Could you share the dimensions of `src` and `distorted_grid`? One of the assumptions here is that the mesh we're warping is very sparse.

**Comment by jeetdholakia** [comment]
```
SRC: 
[[[245 233 228]
  [245 233 228]
  [245 233 228]
  ..., 
  [182 174 170]
  [179 171 168]
  [179 171 168]]

 [[245 233 228]
  [245 233 228]
  [245 233 228]
  ..., 
  [180 171 168]
  [179 170 167]
  [177 169 166]]

 [[245 233 228]
  [245 233 228]
  [245 233 228]
  ..., 
  [180 170 167]
  [181 171 168]
  [181 171 168]]

 ..., 
 [[145 193 205]
  [142 190 203]
  [144 192 204]
  ..., 
  [  6   7   4]
  [  6   7   4]
  [  6   7   4]]

 [[145 193 205]
  [142 190 203]
  [144 192 204]
  ..., 
  [  7   8   6]
  [  6   7   4]
  [  5   6   3]]

 [[144 192 204]
  [144 192 204]
  [142 190 203]
  ..., 
  [  7   8   6]
  [  5   6   3]
  [  5   6   3]]]

```

```
Distorted Grid: 
[[array([[[  9.85654831,  39.09296036]]], dtype=float32), array([[[   9.86312675,  142.00857544]]], dtype=float32), array([[[   9.86976337,  245.81872559]]], dtype=float32), array([[[   9.87645721,  350.53512573]]], dtype=float32), array([[[   9.88321018,  456.16964722]]], dtype=float32), array([[[   9.89002228,  562.73449707]]], dtype=float32), array([[[   9.89689445,  670.24194336]]], dtype=float32), array([[[   9.90382767,  778.70465088]]], dtype=float32), array([[[   9.91082287,  888.13525391]]], dtype=float32), array([[[   9.91788101,  998.54693604]]], dtype=float32)], [array([[[ 113.74214935,   35.842556  ]]], dtype=float32), array([[[ 114.19908142,  138.93202209]]], dtype=float32), array([[[ 114.66000366,  242.91915894]]], dtype=float32), array([[[ 115.12494659,  347.81576538]]], dtype=float32), array([[[ 115.59397888,  453.63381958]]], dtype=float32), array([[[ 116.0671463 ,  560.38549805]]], dtype=float32), array([[[ 116.54450989,  668.08325195]]], dtype=float32), array([[[ 117.02612305,  776.73962402]]], dtype=float32), array([[[ 117.51204681,  886.36761475]]], dtype=float32), array([[[ 118.00232697,  996.98016357]]], dtype=float32)], [array([[[ 218.00621033,   32.58030701]]], dtype=float32), array([[[ 218.91679382,  135.84420776]]], dtype=float32), array([[[ 219.83532715,  240.00894165]]], dtype=float32), array([[[ 220.76190186,  345.08639526]]], dtype=float32), array([[[ 221.69664001,  451.08856201]]], dtype=float32), array([[[ 222.63963318,  558.027771  ]]], dtype=float32), array([[[ 223.59100342,  665.91644287]]], dtype=float32), array([[[ 224.55085754,  774.76727295]]], dtype=float32), array([[[ 225.51931763,  884.59326172]]], dtype=float32), array([[[ 226.49647522,  995.4074707 ]]], dtype=float32)], [array([[[ 322.65081787,   29.30615425]]], dtype=float32), array([[[ 324.01837158,  132.74507141]]], dtype=float32), array([[[ 325.39788818,  237.0880127 ]]], dtype=float32), array([[[ 326.78948975,  342.34692383]]], dtype=float32), array([[[ 328.19338989,  448.53387451]]], dtype=float32), array([[[ 329.60971069,  555.66119385]]], dtype=float32), array([[[ 331.03863525,  663.74151611]]], dtype=float32), array([[[ 332.48031616,  772.78747559]]], dtype=float32), array([[[ 333.93493652,  882.81219482]]], dtype=float32), array([[[ 335.40267944,  993.82879639]]], dtype=float32)], [array([[[ 427.67803955,   26.02002716]]], dtype=float32), array([[[ 429.50592041,  129.634552  ]]], dtype=float32), array([[[ 431.34979248,  234.15631104]]], dtype=float32), array([[[ 433.20986938,  339.59729004]]], dtype=float32), array([[[ 435.08639526,  445.96966553]]], dtype=float32), array([[[ 436.97958374,  553.28582764]]], dtype=float32), array([[[ 438.88961792,  661.55841064]]], dtype=float32), array([[[ 440.81674194,  770.80023193]]], dtype=float32), array([[[ 442.76123047,  881.02435303]]], dtype=float32), array([[[ 444.7232666 ,  992.24414062]]], dtype=float32)], [array([[[ 533.08996582,   22.7218647 ]]], dtype=float32), array([[[ 535.38153076,  126.5125885 ]]], dtype=float32), array([[[ 537.6932373 ,  231.21377563]]], dtype=float32), array([[[ 540.02526855,  336.83746338]]], dtype=float32), array([[[ 542.37792969,  443.39590454]]], dtype=float32), array([[[ 544.75146484,  550.90155029]]], dtype=float32), array([[[ 547.14624023,  659.36706543]]], dtype=float32), array([[[ 549.5625    ,  768.80541992]]], dtype=float32), array([[[ 552.00054932,  879.22973633]]], dtype=float32), array([[[ 554.46063232,  990.65344238]]], dtype=float32)], [array([[[ 638.88879395,   19.41159821]]], dtype=float32), array([[[ 641.64746094,  123.37911987]]], dtype=float32), array([[[ 644.43035889,  228.26034546]]], dtype=float32), array([[[ 647.23779297,  334.06738281]]], dtype=float32), array([[[ 650.07012939,  440.81253052]]], dtype=float32), array([[[ 652.92773438,  548.50830078]]], dtype=float32), array([[[ 655.81085205,  657.1675415 ]]], dtype=float32), array([[[ 658.71990967,  766.80310059]]], dtype=float32), array([[[ 661.6552124 ,  877.42834473]]], dtype=float32), array([[[ 664.61712646,  989.05664062]]], dtype=float32)], [array([[[ 745.07653809,   16.08916092]]], dtype=float32), array([[[ 748.3057251 ,  120.23407745]]], dtype=float32), array([[[ 751.56335449,  225.29595947]]], dtype=float32), array([[[ 754.84973145,  331.28695679]]], dtype=float32), array([[[ 758.16534424,  438.21948242]]], dtype=float32), array([[[ 761.51055908,  546.1060791 ]]], dtype=float32), array([[[ 764.88568115,  654.95965576]]], dtype=float32), array([[[ 768.29125977,  764.79321289]]], dtype=float32), array([[[ 771.7276001 ,  875.62005615]]], dtype=float32), array([[[ 775.19519043,  987.45373535]]], dtype=float32)], [array([[[ 851.65545654,   12.75448513]]], dtype=float32), array([[[ 855.35858154,  117.07740021]]], dtype=float32), array([[[ 859.09442139,  222.32055664]]], dtype=float32), array([[[ 862.86334229,  328.4961853 ]]], dtype=float32), array([[[ 866.66577148,  435.61672974]]], dtype=float32), array([[[ 870.5022583 ,  543.69482422]]], dtype=float32), array([[[ 874.37310791,  652.74346924]]], dtype=float32), array([[[ 878.27893066,  762.7756958 ]]], dtype=float32), array([[[ 882.22015381,  873.80487061]]], dtype=float32), array([[[ 886.19720459,  985.84466553]]], dtype=float32)], [array([[[ 958.62768555,    9.40750504]]], dtype=float32), array([[[ 962.80828857,  113.9090271 ]]], dtype=float32), array([[[ 967.02581787,  219.33407593]]], dtype=float32), array([[[ 971.28082275,  325.69494629]]], dtype=float32), array([[[ 975.57373047,  433.00418091]]], dtype=float32), array([[[ 979.90515137,  541.2744751 ]]], dtype=float32), array([[[ 984.2755127 ,  650.51885986]]], dtype=float32), array([[[ 988.68530273,  760.75042725]]], dtype=float32), array([[[ 993.13519287,  871.98272705]]], dtype=float32), array([[[ 997.62567139,  984.22943115]]], dtype=float32)]]
```

And the error generated is:

```
Traceback (most recent call last):
  File "/Users/jeetdholakia/PycharmProjects/HyperlapseTest/stable.py", line 601, in <module>
    stabilize_video(mp4path, csvpath)
  File "/Users/jeetdholakia/PycharmProjects/HyperlapseTest/stable.py", line 577, in stabilize_video
    prev, focal_length, gyro_delay, gyro_drift);
  File "/Users/jeetdholakia/PycharmProjects/HyperlapseTest/stable.py", line 265, in accumulateRotation
    o = utilities.meshwarp(src, pts_transformed)
  File "/Users/jeetdholakia/PycharmProjects/HyperlapseTest/utilities.py", line 128, in meshwarp
    mapx = np.append([], [ar[:,0] for ar in g_out]).reshape(mapsize).astype('float32')
ValueError: cannot reshape array of size 2367488 into shape (1088,1088,1)
```

**Comment by StevenPuttemans** [comment]
@liquidmetal it seems as there is an error in the reshape. The problem is the values probable get bigger than the range available in float32. How about changing the type to 64bit doubles?

**Comment by jeetdholakia** [comment]
@StevenPuttemans @liquidmetal  I tried the following 

`mapx = np.append([], [ar[:,0] for ar in g_out]).reshape(mapsize).astype('complex64')`
and 
`mapx = np.append([], [ar[:,0] for ar in g_out]).reshape(mapsize).astype('complex128')`
and I'm still getting the same error.

**Comment by jeetdholakia** [comment]
Any ideas?

**Comment by StevenPuttemans** [comment]
@jeetdholakia I am awaiting the feedback of @liquidmetal since it is his code. I am unsure why it does not work.

**Comment by jeetdholakia** [comment]
@liquidmetal the dimensions of `src` is `(1088, 1088, 3)` and using the function `len()` on `distorted_grid`, i get `10`

**Comment by jeetdholakia** [comment]
Any progress on the issue?  @liquidmetal

**Comment by liquidmetal** [comment]
It seems like your input image size should be 2176*1088 (given the total number of elements in `mapx = np.append...` is 2367488). Could you share the image size of `frame` in the `stabilize_video` method in `stable.py`?

**Comment by Kelchli** [comment]
Hi @liquidmetal 

I got a error while running following code:
`output = cv2.perspectiveTransform(np.array([[pixel_x, pixel_y]], dtype="float32"), transform)`

The error message is:
```
output = cv2.perspectiveTransform(np.array([[pixel_x, pixel_y]], dtype="float32"), transform)
cv2.error: /Users/xxx/Desktop/opencv-3.2.0/modules/core/src/matmul.cpp:2271: error: (-215) scn + 1 == m.cols in function perspectiveTransform
```

I modified the codes as:
```
output = cv2.perspectiveTransform(np.array([[[pixel_x, pixel_y]]], dtype="float32"), transform)
            current_row_transformed.append(output[0][0])
```
Then the codes can run without error.
But I still got a issue regarding the odd output from meshwarp() function in utilities.py.
The source is a from from a normal video, the output frame looks like this:
![mesh_test](https://cloud.githubusercontent.com/assets/2536522/25777921/14451090-3321-11e7-8e0d-41d5e9152e01.png)
Distorted grid:
```
[[array([-0.18083344,  0.75028843], dtype=float32), array([ -4.48732972e-02,   1.08754730e+02], dtype=float32), array([  9.10733119e-02,   2.16748413e+02], dtype=float32), array([  2.27006376e-01,   3.24731354e+02], dtype=float32), array([  3.62925917e-01,   4.32703522e+02], dtype=float32), array([  4.98831898e-01,   5.40664978e+02], dtype=float32), array([  6.34724379e-01,   6.48615662e+02], dtype=float32), array([   0.7706033 ,  756.55554199], dtype=float32), array([   0.90646875,  864.48474121], dtype=float32), array([   1.04232061,  972.40319824], dtype=float32)], [array([ 191.72644043,    0.54973757], dtype=float32), array([ 191.8528595 ,  108.56296539], dtype=float32), array([ 191.97926331,  216.56544495], dtype=float32), array([ 192.10565186,  324.55715942], dtype=float32), array([ 192.23202515,  432.53811646], dtype=float32), array([ 192.35838318,  540.50836182], dtype=float32), array([ 192.48474121,  648.46777344], dtype=float32), array([ 192.61108398,  756.41650391], dtype=float32), array([ 192.7374115 ,  864.35449219], dtype=float32), array([ 192.86372375,  972.28167725], dtype=float32)], [array([  3.83664917e+02,   3.49154145e-01], dtype=float32), array([ 383.78179932,  108.37117767], dtype=float32), array([ 383.89865112,  216.38243103], dtype=float32), array([ 384.01547241,  324.38293457], dtype=float32), array([ 384.13232422,  432.37268066], dtype=float32), array([ 384.24914551,  540.35168457], dtype=float32), array([ 384.36593628,  648.31994629], dtype=float32), array([ 384.48272705,  756.27740479], dtype=float32), array([ 384.59951782,  864.22418213], dtype=float32), array([ 384.71627808,  972.16015625], dtype=float32)], [array([  5.75634583e+02,   1.48538053e-01], dtype=float32), array([ 575.74194336,  108.17935181], dtype=float32), array([ 575.84924316,  216.19940186], dtype=float32), array([ 575.95654297,  324.2086792 ], dtype=float32), array([ 576.06378174,  432.20721436], dtype=float32), array([ 576.17108154,  540.19500732], dtype=float32), array([ 576.27832031,  648.17205811], dtype=float32), array([ 576.38555908,  756.13830566], dtype=float32), array([ 576.49279785,  864.09381104], dtype=float32), array([ 576.60003662,  972.03857422], dtype=float32)], [array([  7.67635498e+02,  -5.21106422e-02], dtype=float32), array([ 767.73327637,  107.98749542], dtype=float32), array([ 767.83099365,  216.01634216], dtype=float32), array([ 767.92877197,  324.03442383], dtype=float32), array([ 768.02648926,  432.04174805], dtype=float32), array([ 768.12420654,  540.03833008], dtype=float32), array([ 768.22192383,  648.02410889], dtype=float32), array([ 768.31958008,  755.99914551], dtype=float32), array([ 768.41729736,  863.96343994], dtype=float32), array([ 768.51495361,  971.91699219], dtype=float32)], [array([  9.59667603e+02,  -2.52791971e-01], dtype=float32), array([ 959.75585938,  107.79560852], dtype=float32), array([ 959.84399414,  215.83323669], dtype=float32), array([ 959.93218994,  323.86010742], dtype=float32), array([ 960.02038574,  431.8762207 ], dtype=float32), array([ 960.10852051,  539.8815918 ], dtype=float32), array([ 960.19671631,  647.87615967], dtype=float32), array([ 960.28485107,  755.85998535], dtype=float32), array([ 960.37298584,  863.83306885], dtype=float32), array([ 960.46112061,  971.79541016], dtype=float32)], [array([  1.15173096e+03,  -4.53505933e-01], dtype=float32), array([ 1151.80957031,   107.6036911 ], dtype=float32), array([ 1151.88830566,   215.65011597], dtype=float32), array([ 1151.96691895,   323.68579102], dtype=float32), array([ 1152.04553223,   431.71069336], dtype=float32), array([ 1152.12414551,   539.72485352], dtype=float32), array([ 1152.20275879,   647.72821045], dtype=float32), array([ 1152.28125  ,   755.7208252], dtype=float32), array([ 1152.35986328,   863.70269775], dtype=float32), array([ 1152.43847656,   971.67382812], dtype=float32)], [array([  1.34382556e+03,  -6.54252529e-01], dtype=float32), array([ 1343.89465332,   107.41174316], dtype=float32), array([ 1343.96374512,   215.46696472], dtype=float32), array([ 1344.03283691,   323.51141357], dtype=float32), array([ 1344.10180664,   431.54510498], dtype=float32), array([ 1344.17089844,   539.5680542 ], dtype=float32), array([ 1344.23986816,   647.5802002 ], dtype=float32), array([ 1344.30895996,   755.581604  ], dtype=float32), array([ 1344.37792969,   863.57226562], dtype=float32), array([ 1344.44702148,   971.55218506], dtype=float32)], [array([  1.53595142e+03,  -8.55031788e-01], dtype=float32), array([ 1536.01098633,   107.21975708], dtype=float32), array([ 1536.07043457,   215.28378296], dtype=float32), array([ 1536.12988281,   323.33703613], dtype=float32), array([ 1536.18945312,   431.3795166 ], dtype=float32), array([ 1536.24890137,   539.41125488], dtype=float32), array([ 1536.30834961,   647.43218994], dtype=float32), array([ 1536.36779785,   755.44238281], dtype=float32), array([ 1536.42736816,   863.4418335 ], dtype=float32), array([ 1536.48681641,   971.43054199], dtype=float32)], [array([  1.72810852e+03,  -1.05584371e+00], dtype=float32), array([ 1728.15844727,   107.02774811], dtype=float32), array([ 1728.20837402,   215.10057068], dtype=float32), array([ 1728.25830078,   323.16262817], dtype=float32), array([ 1728.30822754,   431.21389771], dtype=float32), array([ 1728.3581543 ,   539.25439453], dtype=float32), array([ 1728.40808105,   647.28417969], dtype=float32), array([ 1728.45800781,   755.30316162], dtype=float32), array([ 1728.5078125 ,   863.31140137], dtype=float32), array([ 1728.55773926,   971.30883789], dtype=float32)]]
```

I run the codes on Mac OSX 10.12.4 with python2.7 and opencv3.2.0.
Could you please give me any hints for dealing with this issue? Thanks a much!

**Comment by StevenPuttemans** [comment]
@jeetdholakia can you, as pointed out by @liquidmetal provide us the image size?

**Comment by martisan** [comment]
Any update regarding this issue? I'm currently getting the following error:
```
Traceback (most recent call last):
  File "stable.py", line 572, in <module>
    stabilize_video(mp4path, csvpath)
  File "stable.py", line 548, in stabilize_video
    rot = accumulateRotation(frame, delta_theta[0], delta_theta[1], delta_theta[2], timestamps, previous_timestamp, prev, focal_length, gyro_delay, gyro_drift)
  File "stable.py", line 243, in accumulateRotation
    o = utilities.mesh_warp(src, pts_transformed)
  File "/Users/martinj/Downloads/stabilization/utilities.py", line 128, in mesh_warp
    tmp_ary = np.append([], [ary[:, 1] for ary in g_out])
IndexError: index 1 is out of bounds for axis 1 with size 1
```

I've updated my `utilities.py` with the pull request from @Korniluk13:

```
def mesh_warp(src, distorted_grid):
    size = src.shape
    map_size = (size[0], size[1], 1)
    dst = np.zeros(size, dtype=np.uint8)

    quads_per_row = len(distorted_grid) - 1
    quads_per_col = len(distorted_grid[0]) - 1
    pixels_per_row = size[0] / quads_per_row
    pixels_per_col = size[1] / quads_per_col

    pt_src_all = []
    pt_dst_all = []

    for i in distorted_grid:
        pt_src_all.extend(i)

    for x in range(quads_per_row + 1):
        for y in range(quads_per_col + 1):
            pt_dst_all.append([y * pixels_per_col, x * pixels_per_row])

    gx, gy = np.mgrid[0:size[0], 0:size[1]]

    import scipy
    from scipy.interpolate import griddata
    g_out = griddata(np.array(pt_dst_all), np.array(pt_src_all), (gy, gx), method='linear')

    tmp_arx = np.append([], [arx[:, 0] for arx in g_out])
    tmp_ary = np.append([], [ary[:, 1] for ary in g_out])
    map_x = tmp_arx.reshape(map_size).astype('float32')
    map_y = tmp_ary.reshape(map_size).astype('float32')

    dst = cv2.remap(src, map_x, map_y, cv2.INTER_LINEAR)
    cv2.imwrite("/Users/martinj/Downloads/stabilization/images_util/test.png", dst)
    return dst
```

**Comment by naldoxable** [comment]
Hi, i managed to fix some issues due to libraries update. Everything is working on python 3.7 and last opencv exept this 
` o = utilities.mesh_warp(src, pts_transformed)`. do you have any suggest? seems an array dimension issue. Thanks

**Comment by JoeHowse** [comment]
@naldoxable Could you please test whether the changes in pull request https://github.com/OpenCVBlueprints/OpenCVBlueprints/pull/23/ help with this issue? Thanks!

**Comment by naldoxable** [comment]
Hi, thanks. This is the log:
```
final_simplex: (array([[ 5.21145874e+02,  5.34411494e-04, -3.50100878e-03,
        -1.79698923e-03, -2.83991436e-04,  2.81610945e-03],
       [ 5.21146687e+02,  5.34398726e-04, -3.50102290e-03,
        -1.79700840e-03, -2.83988176e-04,  2.81612614e-03],
       [ 5.21146416e+02,  5.34436957e-04, -3.50100378e-03,
        -1.79698610e-03, -2.84006730e-04,  2.81610519e-03],
       [ 5.21146214e+02,  5.34437342e-04, -3.50101619e-03,
        -1.79696851e-03, -2.84022818e-04,  2.81610663e-03],
       [ 5.21146435e+02,  5.34434250e-04, -3.50101700e-03,
        -1.79697661e-03, -2.84018013e-04,  2.81610877e-03],
       [ 5.21146498e+02,  5.34431909e-04, -3.50100693e-03,
        -1.79701045e-03, -2.84005214e-04,  2.81611407e-03],
       [ 5.21146305e+02,  5.34432509e-04, -3.50101101e-03,
        -1.79693242e-03, -2.84021240e-04,  2.81609095e-03]]), array([175263.16080083, 175263.16084313, 175263.1610802 , 175263.16114665,
       175263.16119521, 175263.16141519, 175263.16149609]))
           fun: 175263.16080083244
       message: 'Optimization terminated successfully.'
          nfev: 358
           nit: 196
        status: 0
       success: True
             x: array([ 5.21145874e+02,  5.34411494e-04, -3.50100878e-03, -1.79698923e-03,
       -2.83991436e-04,  2.81610945e-03])
Focal length = 521.145874
Gyro delay   = 0.000534
Gyro drift   = (-0.003501, -0.001797, -0.000284)
Shutter duration= 0.002816
Processing frame 0
    timestamp = 0.0 ns
Processing frame 1
    timestamp = 33288888.88888889 ns
Traceback (most recent call last):
  File ".\stabilize.py", line 575, in <module>
    stabilize_video(mp4path, csvpath)
  File ".\stabilize.py", line 551, in stabilize_video
    rot = accumulateRotation(frame, delta_theta[0], delta_theta[1], delta_theta[2], timestamps, previous_timestamp, prev, focal_length, gyro_delay, gyro_drift)
  File ".\stabilize.py", line 245, in accumulateRotation
    o = utilities.meshwarp(src, pts_transformed)
  File "C:\Users\naldo\Desktop\imu_stabilizer\python\utilities.py", line 117, in meshwarp
    tmp_ary = np.append([], [ary[:, 1] for ary in g_out])
  File "C:\Users\naldo\Desktop\imu_stabilizer\python\utilities.py", line 117, in <listcomp>
    tmp_ary = np.append([], [ary[:, 1] for ary in g_out])
IndexError: index 1 is out of bounds for axis 1 with size 1
```
