### ISSUE TITLE
Chapter 7  - Error in Python Code

### ISSUE THREAD

**Issue by martisan** [OpenCVBlueprints/OpenCVBlueprints#25]
Good day,

I'm currently working on Chapter 7. I've created an Android application to capture video and write to the gyro file.

When I try to use the captured video and gyro file with `stable.py` I get the following error:
```Traceback (most recent call last):
  File "stable.py", line 572, in <module>
    stabilize_video(mp4path, csvpath)
  File "stable.py", line 548, in stabilize_video
    rot = accumulateRotation(frame, delta_theta[0], delta_theta[1], delta_theta[2], timestamps, previous_timestamp, prev, focal_length, gyro_delay, gyro_drift)
  File "stable.py", line 237, in accumulateRotation
    output = cv2.perspectiveTransform(np.array([[pixel_x, pixel_y]], dtype="float32"), transform)
cv2.error: /tmp/opencv-20170224-1869-10nlf6f/opencv-2.4.13.2/modules/core/src/matmul.cpp:1943: error: (-215) scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F) in function perspectiveTransform
```

Any idea as to what the problem could be?

**Comment by StevenPuttemans** [comment]
Basically `error: (-215) scn + 1 == m.cols && (depth == CV_32F || depth == CV_64F)` tells me that 2 things could wrong

1. The type of the input data is not 32 or 64 bit float. However, your code clearly asks for 32bit floating point precision. So this will not be it.
2. The assert `scn + 1 == m.cols` failed. Now take a look into the code to see what scn should be and thus which input matrix is incorrect.

**Comment by martisan** [comment]
Hi @StevenPuttemans,
Thank you for the reply. I've had a look at the code.
If I print `print "Array: %s" % np.array([[pixel_x, pixel_y]], dtype="float32")` I see `Array: [[ 0.  0.]]`.

I also noticed that `pixel_x` and `pixel_y` = 0.

**Comment by StevenPuttemans** [comment]
> I also noticed that pixel_x and pixel_y = 0

And that is exactly the issue why this is happening. where is `pixel_x` and `pixel_y` calculated?

**Comment by martisan** [comment]
Both `pixel_x` and `pixel_y` are calculated here:

```
def accumulateRotation(src, theta_x, theta_y, theta_z, timestamps, prev, current, f, gyro_delay=None, gyro_drift=None, shutter_duration=None):
    if prev == current:
        return src

    pts = []
    pts_transformed = []
    for x in range(10):
        current_row = []
        current_row_transformed = []
        pixel_x = x * (src.shape[1] / 10)
        for y in range(10):
            pixel_y = y * (src.shape[0] / 10)

            current_row.append( [pixel_x, pixel_y] )

            if shutter_duration:
                y_timestamp = current + shutter_duration * (pixel_y - src.shape[0]/2)
            else:
                y_timestamp = current

            transform = getAccumulatedRotation(src.shape[1], src.shape[0], theta_x, theta_y, theta_z, timestamps, prev, current, f, gyro_delay, gyro_drift)
            print "Array: %s" % np.array([[pixel_x, pixel_y]], dtype="float32")
            output = cv2.perspectiveTransform(np.array([[pixel_x, pixel_y]], dtype="float32"), transform)
            print "Output = %s" % output
            current_row_transformed.append(output)

        pts.append(current_row)
        pts_transformed.append(current_row_transformed)

    o = utilities.meshwarp(src, pts_transformed)
    return o
```
I primarily develop for iOS, so I'm not a Python expert. Still trying to figure out why they would be 0.

**Comment by naldoxable** [comment]
due to libraries update you have to change np.array([[pixel_x, pixel_y]] to np.array([[[pixel_x, pixel_y]]] in order to use 3 dimensions. Anyway another issue is coming from a reshape and I haven't understood how to fix it yet.. (tagged with bug in the Issues)

**Comment by icer1** [comment]
> 

I have same problem now.

Traceback (most recent call last):
  File ".\stable.py", line 582, in <module>
    stabilize_video(mp4path, csvpath)
  File ".\stable.py", line 558, in stabilize_video
    rot = accumulateRotation(frame, delta_theta[0], delta_theta[1], delta_theta[2], timestamps, previous_timestamp, prev, focal_length, gyro_delay, gyro_drift)
  File ".\stable.py", line 253, in accumulateRotation
    o = utilities.meshwarp(src, pts_transformed)
  File ".\utilities.py", line 116, in meshwarp
    mapx = np.append([], [ar[:,0] for ar in g_out]).reshape(mapsize).astype('float32')
ValueError: total size of new array must be unchanged

**Comment by fdy6666** [comment]
May I ask if the above problem has been solved? I also encountered the same problem, which can not be solved
